name: mantissocial
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^3.3.2
  apple_sign_in: ^0.1.0
  autocomplete_textfield: ^1.7.3
  cached_network_image: ^2.4.0
  checkbox_grouped: ^0.6.1
  cloud_firestore: ^0.14.3+1
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.0.0
  flutter_mapbox_autocomplete: ^1.0.4
  flutter_ringtone_player: ^3.0.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  geocoder: ^0.2.1
  google_mobile_ads: ^0.12.1
  image_cropper: ^1.4.0
  image_picker: ^0.6.7+14
  in_app_purchase: ^0.3.4+16
  intl: ^0.16.1
  location: ^3.1.0
  path_provider: ^2.0.1
  permission_handler: ^5.0.1+1
  pin_code_fields: ^7.0.0
  rflutter_alert: ^2.0.2
  share: ^2.0.1
  shimmer: ^1.1.2
  swipe_stack: ^1.0.0
  url_launcher: ^6.0.3
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/Icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/auth/
    - asset/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
