List<String> suggestions = [
"Arsom Silp Institute of the Arts",
"Asia-Pacific International University",
"Asian Institute of Technology",
"Asian University",
"Assumption University",
"Bangkok School of Management",
"Bangkok Suvarnabhumi University",
"Bangkok Thonburi University",
"Bangkok University",
"Banglamung Inter-Tech Technological College",
"Bansomdejchaopraya Rajabhat University",
"Boonthavorn Technology College",
"Bundit Boriharnthurakit College",
"Bunditpatanasilpa Institute",
"Burapha University",
"Buri Ram Rajabhat University",
"Cambridge College (Thailand)",
"Chaiyaphum Rajabhat University",
"Chalermkarnchana University",
"Chandrakasem Rajabhat University",
"Chaopraya University",
"Chiang Mai Rajabhat University",
"Chiang Mai University",
"Chiang Rai Rajabhat University",
"Chiangrai College",
"Chitralada Technology Institute",
"Christian University of Thailand",
"Chulabhorn Graduate Institute",
"Chulachomklao Royal Military Academy",
"Chulalongkorn University",
"Civil Aviation Training Center",
"College of Asian Scholars",
"Command and General Staff College",
"Dhonburi Rajabhat University",
"Dhurakij Pundit University",
"Don Bosco Technological College",
"Dusit Thani College",
"E-sarn University",
"Eastern Asia University",
"Ekawan Vocational College",
"Fatoni University",
"Galileo Maritime Academy",
"Hatyai University",
"HRH Princess Chulabhorn College of Medical Science",
"Huachiew Chalermprakiet University",
"Institute of Technology Ayothaya",
"International Buddhist College",
"International Hotel and Tourism Industry Management School",
"Irrigation College",
"Joint Graduate School of Energy and Environment",
"Judge Advocate General School Thailand",
"Kalasin University",
"Kamphaeng Phet Rajabhat University",
"Kanchanaburi Rajabhat University",
"Kantana Institute",
"Kantharalak Technical College",
"Kasem Bundit University",
"Kasetsart University",
"Khon Kaen University",
"King Mongkut's Institute of Technology Ladkrabang",
"King Mongkut's University of Technology North Bangkok",
"King Mongkut's University of Technology Thonburi",
"Krirk University",
"Lampang Inter-Tech College",
"Lampang Rajabhat University",
"Learning Institute For Everyone",
"Loei Rajabhat University",
"Loengnoktha Industrial and Community Education College",
"Lumnamping College",
"Mae Fah Luang University",
"Maejo University",
"Maha Sarakham Rajabhat University",
"Mahachulalongkornrajavidyalaya University",
"Mahamakut Buddhist University",
"Mahanakorn University of Technology",
"Mahasarakham University",
"Mahidol University",
"Merchant Marine Training Center",
"Muban Chom Bung Rajabhat University",
"Nakhon Pathom Rajabhat University",
"Nakhon Phanom University",
"Nakhon Ratchasima Rajabhat University",
"Nakhon Sawan Rajabhat University",
"Nakhon Si Thammarat Rajabhat University",
"Nakhonratchasima College",
"Nakhonratchasima Polytechnic College",
"Nakhonratchasima Technical College",
"Namphong Technical College",
"Naresuan University",
"Nation University (Yonok University)",
"National Defence College",
"National Institute of Development Administration (NIDA)",
"Navaminda Kasatriyadhiraj Royal Thai Air Force Academy",
"Navamindradhiraj University",
"Nonthaburi Technical College",
"North Bangkok University",
"North Chiang Mai University",
"North Eastern University",
"Northern College",
"Panyapiwat Institute of Management",
"Pathumthani Technical College",
"Pathumthani University",
"Pathumwan Institute of Technology",
"Payap University",
"Phanomwan College of Technology",
"Phatthalung Technical College",
"Phetchabun Rajabhat University",
"Phetchaburi Rajabhat University",
"Phitsanulok University",
"Phramongkutklao College of Medicine",
"Phranakhon Rajabhat University",
"Phranakhon Si Ayutthaya Rajabhat University",
"Phuket Rajabhat University",
"Pibulsongkram Rajabhat University",
"Police Nursing College",
"Praboromarajchanok Institute",
"Prince of Songkla University",
"Princess Galyani Vadhana Institute of Music",
"Princess of Naradhiwas University",
"Raffles International College (Bangkok)",
"Rajamangala University of Technology Isan",
"Rajamangala University of Technology Krungthep",
"Rajamangala University of Technology Lanna",
"Rajamangala University of Technology Phra Nakhon",
"Rajamangala University of Technology Rattanakosin",
"Rajamangala University of Technology Srivijaya",
"Rajamangala University of Technology Suvarnabhumi",
"Rajamangala University of Technology Tawan-ok",
"Rajamangala University of Technology Thanyaburi",
"Rajanagarindra Rajabhat University",
"Rajapark Institute",
"Rakthai Namyuen Business Administration Technological College",
"Rambhai Barni Rajabhat University",
"Ramkhamhaeng University",
"Rangsit University",
"Ratchathani University",
"Rattana Bundit University",
"Roi Et Rajabhat University",
"Royal Police Cadet Academy",
"Royal Thai Air Force Nursing College",
"Royal Thai Navy Academy",
"Royal Thai Navy College of Nursing",
"SAE Institute Bangkok",
"Saengtham College",
"Saint John\'s University",
"Saint Louis College",
"Sakon Nakhon Rajabhat University",
"Samutprakan Technical College",
"Santapol College",
"Shinawatra University",
"Siam Technology College",
"Siam Thanyaburi Child and Elderly Care School",
"Siam University",
"Silpakorn University",
"Singburi Vocational College",
"Sisaket Rajabhat University",
"Songkhla Rajabhat University",
"Songphinong Industrial and Community Education College",
"South-East Asia University",
"Southeast Bangkok College",
"Southern College of Technology",
"Srinakharinwirot University",
"Sripatum University",
"Srisavarindhira Thai Red Cross Institute of Nursing",
"Sriworakarn Technology College",
"St Theresa International College",
"Stamford International University",
"Suan Dusit University",
"Suan Sunandha Rajabhat University",
"Sukhothai Thammathirat Open University",
"Supervisory Unit (Office of Vocational Education Commission)",
"Suphanburi Technical College",
"Suranaree University of Technology",
"Suratthani Rajabhat University",
"Surin Rajabhat University",
"Tapee University",
"Thai-Nichi Institute of Technology",
"Thailand Advanced Institute of Science and Technology-Tokyo Institute of Technology (TAIST-Tokyo Tech)",
"Thailand Graduate Institute of Science and Technology (TGIST)",
"Thailand National Sports University",
"Thaksin University",
"Thammasat University",
"The Eastern University of Management and Technology",
"The Far Eastern University",
"The University of Central Thailand",
"Thepsatri Rajabhat University",
"Thonburi University",
"Thongsook College",
"Ubon Ratchathani Rajabhat University",
"Ubon Ratchathani University",
"Udon Thani Rajabhat University",
"Udonthani Vocational College",
"Unicentre College Thailand",
"University of Phayao",
"University of the Thai Chamber of Commerce",
"Uttaradit Rajabhat University",
"Valaya Alongkorn Rajabhat University",
"Vidyasirimedhi Institute of Science and Technology (VISTEC)",
"Vongchavalitkul University",
"Walailak University",
"Webster University Thailand",
"Western University",
"Yala Rajabhat University",
];
